[[constraint]]
  name = "k8s.io/kubernetes"
  version = "~1.11.4"

[[override]]
  name = "k8s.io/apimachinery"
  branch = "release-1.11"

[[override]]
  name = "k8s.io/client-go"
  branch = "release-8.0"

[[constraint]]
  name = "github.com/sylabs/singularity"
  source = "github.com/cclerget/singularity"
  branch = "master-oci"

[[constraint]]
  name = "github.com/sylabs/sif"
  version = "1.0.1"

[[constraint]]
  name = "github.com/kr/pty"
  version = "v1.1.3"

[[constraint]]
  name = "github.com/opencontainers/selinux"
  version = "v1.0.0-rc1"

[[constraint]]
  name = "github.com/opencontainers/runc"
  version = "v1.0.0-rc6"

# patched fork from github.com/golang/crypto
[[override]]
  branch = "master"
  name = "golang.org/x/crypto"
  source = "github.com/sylabs/golang-x-crypto"

[prune]
  go-tests = true
  unused-packages = true
