# unix socket to serve CRI requests on, required
# default: /var/run/singularity.sock
listenSocket: /var/run/singularity.sock

# directory to store all pulled images in, required
# default: /var/lib/singularity
storageDir: /var/lib/singularity

# address to serve streaming requests on (exec, attach, portforward), optional
# default: 127.0.0.1:12345
streamingURL:

# directory to look for CNI plugin binaries, optional
# default: /opt/cni/bin
cniBinDir:

# directory to look for CNI network configuration files, optional
# default: /etc/cni/net.d
cniConfDir:

# directory to store currently running pods and containers, required
# default: /var/run/singularity
baseRunDir: /var/run/singularity

# directory where all container logs and configs will be stored upon removal
# default:
trashDir:

# whether CRI needs to log all requests and responses
# default: false
debug:
